[workspace]
resolver = "2"
members = [
  "ieee1905-core",
  "ieee1905-tests",
  "rbus-sys",
  "rbus-core",
  "rbus-provider",
]

[profile.release]
strip = true
debug = false
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
