# release.toml

# Only allow releases from main
allow-branch = ["main"]

# Do not publish to crates.io
publish = false

# Tagging according to Rust sandard
tag-name = "v{{version}}"
tag-message = "Release {{crate_name}} v{{version}}"
push-remote = "origin"

# Commit messages
consolidate-commits = true
shared-version = true
pre-release-commit-message = "chore(release): {{version}}"

# Run checks before releasing (set to false if you donâ€™t want tests to run)
verify = false

# We sign everything
sign-commit = true
sign-tag = true
