[package]
name = "rbus-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
rbus-core = { path = "../rbus-core" }
bstr = "1.12.1"
thiserror = "2.0.17"
indexmap = "2.12.1"
parking_lot = "0.12.5"
