[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-args=-Wl,--unresolved-symbols=ignore-all"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "link-args=-Wl,--unresolved-symbols=ignore-all"]
